guidance:
  pretrained_model_name_or_path: "stabilityai/stable-video-diffusion-img2vid-xt"
  enable_memory_efficient_attention: False
  enable_sequential_cpu_offload: False
  enable_attention_slicing: False
  enable_channels_last_format: False
  guidance_scale: 100.
  grad_clip: null
  half_precision_weights: True

  min_step_percent: 0.02
  max_step_percent: 0.98
  max_step_percent_annealed: 0.5
  anneal_start_step: null

  use_sjc: False
  var_red: True
  weighting_strategy: "sds"

  view_dependent_prompting: True

  low_ram_vae: -1 ## set to a positive integer (the number of frames with gradient) if hope to use this
